### ISSUE TITLE
Modularize summary logic 

### ISSUE THREAD

**Issue by sakshampandey27** [nihar4276/slackpoint-group18#12]
Currently, entire summary logic is written in app.py.
We should create a separate file and class for the summary command and should only call those functions from app.py

**Comment by nihar4276** [comment]
Thanks for pointing out, I will take care of this

**Comment by pjhamb** [comment]
That's a good idea, this will be better for modularizing our code base

**Comment by nihar4276** [comment]
Finished https://github.com/nihar4276/slackpoint-group18/pull/24
