### ISSUE TITLE
/taskdone command is not working

### ISSUE THREAD

**Issue by smanishs175** [nihar4276/slackpoint-group18#2]
Hi, 

When I implemented few commands, /taskdone command is not working . Purpose of this command is to mark completed task. @nihar4276 , can you check the error if possible

Thanks

**Comment by nihar4276** [comment]
Yeah you are right, I will have a look at it.

**Comment by nihar4276** [comment]
Fixed with https://github.com/nihar4276/slackpoint-group18/pull/5
